### ISSUE TITLE
Doesn't seem to be working?

### ISSUE THREAD

**Issue by dieggsy** [dkarter/AlfredNetflixSearchWorkflow#1]
Great workflow! However, recently doesn't seem to be working for me. Goes to "Searching Netflix..." and then goes to alfred fallback search. Is this just me?

**Comment by dkarter** [comment]
Thanks for the bug report!
Netflix changed their internal APIs so I have to update my API wrapper to support this change.
I should have time this weekend to try and fix it.

**Comment by christianmagill** [comment]
Can't wait! Great workflow, I use it all the time.

**Comment by dkarter** [comment]
Sorry guys, I tried.. Netflix has gotten extra tricky about their internal APIs. They keep changing their urls every internal deploy to some random hash. I know if I work on this hard enough and for longer period of time I can probably work around all of their changes, but seeing that I don't really use this workflow anymore (I got a TV) I prefer not spending my time on it. Pull requests are welcome.

**Comment by christianmagill** [comment]
Thanks for your efforts. It was nice while it lasted.

**Comment by dieggsy** [comment]
@dkarter just going through some of my old open issues, you should consider archiving this repo
